# -*- coding: utf-8 -*-
"""letras-taylor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGToG90WzjYIFuqt-B3WWk-8z8axPB-L
"""

!pip install requests beautifulsoup4

import os
import re
import time
import urllib.parse
import requests
from bs4 import BeautifulSoup

def extrair_todas_as_letras():
    url_principal = "https://letras.taylorswift.com.br/album-the-life-of-a-showgirl/"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
    }

    print(f"A aceder à página principal: {url_principal}...")
    try:
        res = requests.get(url_principal, headers=headers)
        res.raise_for_status()
    except Exception as e:
        print(f"Erro ao aceder à página principal: {e}")
        return

    soup = BeautifulSoup(res.text, 'html.parser')

    # Procura por todos os links do site
    links_musicas = []
    for a in soup.find_all('a', href=True):
        href = a['href']
        # Filtra os links para garantir que pertencem ao site e não são páginas institucionais ou categorias
        if "letras.taylorswift.com.br" in href:
            if not any(x in href for x in ['por-nome','wp-content', 'category', 'tag', 'author', 'page/', 'traducoes']):
                if href not in links_musicas:
                    links_musicas.append(href)

    print(f"Foram detetados {len(links_musicas)} potenciais links de músicas.")

    # Criar ou limpar o ficheiro final
    ficheiro_saida = "Letras_TLOAS_Taylor_Swift.txt"
    with open(ficheiro_saida, "w", encoding="utf-8") as f:
        f.write("==================================================\n")
        f.write("      TAYLOR SWIFT - TLOAS TV     \n")
        f.write("==================================================\n\n")

    # Percorrer cada link e extrair a letra
    contador = 0
    for link in sorted(links_musicas):
        contador += 1
        print(f"[{contador}/{len(links_musicas)}] A baixar: {link}")

        try:
            response = requests.get(link, headers=headers)
            if response.status_code != 200:
                print(f"Aviso: Não foi possível carregar a página (Status {response.status_code})")
                continue

            page_soup = BeautifulSoup(response.text, 'html.parser')

            # Captura o título da música (geralmente h1)
            titulo_elem = page_soup.find('h1')
            titulo = titulo_elem.text.strip() if titulo_elem else "Música sem Título"

            # Tenta encontrar a div principal que armazena a letra
            # A maioria dos temas WordPress utiliza a classe '.entry-content' ou tags '<article>'
            conteudo_div = page_soup.find(class_='entry-content') or page_soup.find('article')

            if conteudo_div:
                # Remove elementos indesejados se existirem dentro do texto (como botões de partilha ou anúncios)
                for element in conteudo_div.find_all(['script', 'style', 'noscript', 'iframe']):
                    element.decompose()

                letra_texto = conteudo_div.get_text(separator="\n").strip()
            else:
                # Fallback caso a estrutura mude
                letra_texto = page_soup.get_text(separator="\n").strip()

            # Limpeza básica de quebras de linha excessivas
            letra_texto = re.sub(r'\n{3,}', '\n\n', letra_texto)

            # Escreve de forma estruturada no documento de texto
            with open(ficheiro_saida, "a", encoding="utf-8") as f:
                f.write(f"Title: {titulo}\n")
                f.write(f"Link Original: {link}\n")
                f.write("-" * 40 + "\n")
                f.write(letra_texto)
                f.write("\n\n" + "="*50 + "\n\n")

            # Pausa de cortesia para não sobrecarregar o servidor do fã-site
            time.sleep(1)

        except Exception as e:
            print(f"Erro ao processar o link {link}: {e}")

    print(f"\nConcluído! O arquivo '{ficheiro_saida}' foi gerado com sucesso.")

if __name__ == "__main__":
    extrair_todas_as_letras()